// frontend/src/app/features/admin/admin.component.ts
import {
  Component,
  OnInit,
  signal,
  computed,
  inject,
  DestroyRef,
} from '@angular/core';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { RegistryService } from '../../core/services/registry.service';
import { IconComponent } from '../../shared/components/icon/icon.component';
import { TypeBadgeComponent } from '../../shared/components/type-badge/type-badge.component';
import { TYPE_META } from '../../shared/constants/type-meta.constants';
import { timeAgo } from '../../shared/utils/time-ago';
import {
  AppStats,
  PendingEntry,
  PendingStats,
  RiskLevel,
  EntryType,
  RegistryEntry,
  Server,
  Tool,
} from '../../shared/types';

type QueueFilter = 'all' | 'server' | 'tool' | 'skill' | 'high';

interface Toast {
  name: string;
  verdict: string;
}

interface KpiCard {
  value: string | number;
  label: string;
  suffix?: string;
  trend?: string;
  up?: boolean;
  danger?: boolean;
}

@Component({
  selector: 'app-admin',
  standalone: true,
  imports: [RouterLink, FormsModule, IconComponent, TypeBadgeComponent],
  templateUrl: './admin.component.html',
})
export class AdminComponent implements OnInit {
  private readonly registry = inject(RegistryService);
  private readonly destroyRef = inject(DestroyRef);

  readonly items = signal<PendingEntry[]>([]);
  readonly loading = signal(true);
  readonly error = signal<string | null>(null);
  readonly actionInProgress = signal<string | null>(null);
  readonly filter = signal<QueueFilter>('all');
  readonly toast = signal<Toast | null>(null);
  readonly registryStats = signal<AppStats | null>(null);
  readonly pendingStats = signal<PendingStats | null>(null);

  /** Accessible reject / request-changes dialog state (replaces window.prompt). */
  readonly rejectDialog = signal<{ entry: PendingEntry; mode: 'reject' | 'changes' } | null>(null);
  readonly rejectReason = signal('');
  readonly rejectError = signal<string | null>(null);

  readonly filteredItems = computed(() => {
    const filter = this.filter();
    const list = this.items();
    if (filter === 'all') return list;
    if (filter === 'high') {
      return list.filter(i => i.risk === 'high');
    }
    return list.filter(i => i.entry.type === filter);
  });

  readonly kpis = computed((): KpiCard[] => {
    const list = this.items();
    const stats = this.registryStats();
    const pending = this.pendingStats();
    const highRisk = pending?.highRiskPending ?? list.filter(i => i.risk === 'high' || i.risk === 'critical').length;
    const published = stats?.totalEntries ?? 0;
    const approvedThisWeek = pending?.approvedThisWeek ?? 0;
    const avgReview = pending?.avgReviewTimeMinutes;

    return [
      { value: pending?.pendingCount ?? list.length, label: 'Awaiting review' },
      {
        value: published,
        label: 'Published',
        trend: approvedThisWeek > 0 ? `+${approvedThisWeek} this week` : undefined,
        up: approvedThisWeek > 0,
      },
      { value: highRisk, label: 'High risk flagged', danger: true },
      {
        value: avgReview ?? '—',
        label: 'Avg time to review',
        suffix: avgReview != null ? 'min' : undefined,
      },
    ];
  });

  readonly filterTabs: Array<{ id: QueueFilter; label: string }> = [
    { id: 'all', label: 'All' },
    { id: 'server', label: 'Servers' },
    { id: 'tool', label: 'Tools' },
    { id: 'skill', label: 'Skills' },
    { id: 'high', label: 'High risk' },
  ];

  readonly timeAgo = timeAgo;
  readonly typeMeta = TYPE_META;

  ngOnInit(): void {
    this.loadStats();
    this.loadPending();
  }

  loadStats(): void {
    this.registry
      .getStats()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({ next: s => this.registryStats.set(s) });

    this.registry
      .getPendingStats()
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({ next: s => this.pendingStats.set(s) });
  }

  loadPending(): void {
    this.loading.set(true);
    this.error.set(null);

    this.registry
      .getPending({ status: 'pending' })
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: result => {
          this.items.set(result.hits);
          this.loading.set(false);
        },
        error: () => {
          this.error.set('Failed to load pending entries.');
          this.loading.set(false);
        },
      });
  }

  setFilter(filter: QueueFilter): void {
    this.filter.set(filter);
  }

  /** Roving-tabindex arrow-key navigation for the queue filter tablist. */
  onFilterKeydown(event: KeyboardEvent, currentId: QueueFilter): void {
    const tabs = this.filterTabs;
    const idx = tabs.findIndex((t) => t.id === currentId);
    if (idx < 0) return;

    let next = idx;
    switch (event.key) {
      case 'ArrowRight':
      case 'ArrowDown':
        next = (idx + 1) % tabs.length;
        break;
      case 'ArrowLeft':
      case 'ArrowUp':
        next = (idx - 1 + tabs.length) % tabs.length;
        break;
      case 'Home':
        next = 0;
        break;
      case 'End':
        next = tabs.length - 1;
        break;
      default:
        return;
    }

    event.preventDefault();
    const nextTab = tabs[next];
    if (nextTab) {
      this.setFilter(nextTab.id);
      document.getElementById(`filter-tab-${nextTab.id}`)?.focus();
    }
  }

  tabLabel(tab: { id: QueueFilter; label: string }): string {
    if (tab.id === 'all') return `All · ${this.items().length}`;
    return tab.label;
  }

  typeIcon(entry: Partial<RegistryEntry>): string {
    const type = entry.type ?? 'server';
    return TYPE_META[type as EntryType]?.icon ?? 'server';
  }

  entryType(entry: Partial<RegistryEntry>): EntryType {
    return (entry.type ?? 'server') as EntryType;
  }

  entrySlug(entry: Partial<RegistryEntry>): string {
    return entry.slug ?? '';
  }

  entrySummary(entry: Partial<RegistryEntry>): string {
    return entry.summary ?? '';
  }

  entryPublisher(entry: Partial<RegistryEntry>): string {
    return entry.publisher ?? 'Unknown';
  }

  entryTransports(entry: Partial<RegistryEntry>): string[] {
    if (entry.type === 'server') {
      return (entry as Server).transports ?? [];
    }
    return [];
  }

  entryAuth(entry: Partial<RegistryEntry>): string | null {
    if (entry.type === 'server') {
      return (entry as Server).auth ?? null;
    }
    return (entry as { auth?: string }).auth ?? null;
  }

  entryToolCount(entry: Partial<RegistryEntry>): number {
    if (entry.type === 'server') {
      return (entry as Server).tools?.length ?? 0;
    }
    return 0;
  }

  entryParent(entry: Partial<RegistryEntry>): string | null {
    if (entry.type === 'tool') {
      return (entry as Tool).parentServer ?? null;
    }
    return null;
  }

  riskBarClass(risk: RiskLevel): string {
    if (risk === 'critical') return 'risk-high';
    return `risk-${risk}`;
  }

  flagHighClass(risk: RiskLevel): boolean {
    return risk === 'high';
  }

  riskBadgeTone(risk: RiskLevel): string {
    if (risk === 'critical' || risk === 'high') return 'danger';
    if (risk === 'medium') return 'warn';
    return 'ok';
  }

  riskLabel(risk: RiskLevel): string {
    return risk;
  }

  approve(entry: PendingEntry): void {
    this.actionInProgress.set(entry.id);

    this.registry
      .approvePending(entry.id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.removeItem(entry);
          this.actionInProgress.set(null);
          this.showToast(entry.entry.name ?? 'Entry', 'approved');
          this.loadStats();
        },
        error: () => {
          this.actionInProgress.set(null);
          this.showToast(entry.entry.name ?? 'Entry', 'approval failed');
        },
      });
  }

  requestChanges(entry: PendingEntry): void {
    this.openRejectDialog(entry, 'changes');
  }

  reject(entry: PendingEntry): void {
    this.openRejectDialog(entry, 'reject');
  }

  private openRejectDialog(entry: PendingEntry, mode: 'reject' | 'changes'): void {
    this.rejectReason.set('');
    this.rejectError.set(null);
    this.rejectDialog.set({ entry, mode });
  }

  cancelRejectDialog(): void {
    this.rejectDialog.set(null);
  }

  confirmRejectDialog(): void {
    const ctx = this.rejectDialog();
    if (!ctx) return;
    const text = this.rejectReason().trim();
    if (text.length < 10) {
      this.rejectError.set('Please enter at least 10 characters.');
      return;
    }
    const reason = ctx.mode === 'changes' ? `Changes requested: ${text}` : text;
    const verdict = ctx.mode === 'changes' ? 'changes requested' : 'rejected';
    this.rejectDialog.set(null);
    this.rejectEntry(ctx.entry, reason, verdict);
  }

  private rejectEntry(entry: PendingEntry, reason: string, verdict: string): void {
    this.actionInProgress.set(entry.id);

    this.registry
      .rejectPending(entry.id, reason)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: () => {
          this.removeItem(entry);
          this.actionInProgress.set(null);
          this.showToast(entry.entry.name ?? 'Entry', verdict);
          this.loadStats();
        },
        error: () => {
          this.actionInProgress.set(null);
          this.showToast(entry.entry.name ?? 'Entry', `${verdict} failed`);
        },
      });
  }

  private removeItem(entry: PendingEntry): void {
    this.items.update(list => list.filter(e => e.id !== entry.id));
  }

  private showToast(name: string, verdict: string): void {
    this.toast.set({ name, verdict });
    setTimeout(() => this.toast.set(null), 2600);
  }
}

<div class="container page">
  <div class="page-head" style="display:flex;align-items:flex-end;justify-content:space-between;flex-wrap:wrap;gap:16px;">
    <div>
      <div class="eyebrow">Governance</div>
      <h1 class="h1">Moderation queue</h1>
      <p class="lede">Review what publishers want to add. Approve, request changes, or reject — least privilege is the default.</p>
    </div>
    <a routerLink="/admin/policy" class="btn btn-secondary btn-sm">
      <app-icon name="shield" [size]="14" aria-hidden="true"></app-icon>
      Policy settings
    </a>
  </div>

  <div class="admin-stats" role="list" aria-label="Queue statistics">
    @if (statsError()) {
      <div class="callout" role="alert" style="grid-column: 1 / -1; margin-bottom: 8px">
        {{ statsError() }}
        <button type="button" class="inline-link" (click)="loadStats()">Retry</button>
      </div>
    }
    @for (kpi of kpis(); track kpi.label) {
      <div class="kpi" role="listitem">
        <div
          class="kpi-n"
          [style.color]="kpi.danger && +kpi.value > 0 ? 'var(--danger)' : null"
        >
          {{ kpi.value }}@if (kpi.suffix) {
            <span style="font-size:14px;color:var(--muted);font-weight:500;"> {{ kpi.suffix }}</span>
          }
        </div>
        <div class="kpi-l">{{ kpi.label }}</div>
        @if (kpi.trend) {
          <div class="kpi-trend" [style.color]="kpi.up ? 'var(--ok)' : 'var(--muted)'">{{ kpi.trend }}</div>
        }
      </div>
    }
  </div>

  <div class="tabs" style="margin-bottom:20px;" role="tablist" aria-label="Filter queue">
    @for (tab of filterTabs; track tab.id) {
      <button
        type="button"
        class="tab"
        [class.on]="filter() === tab.id"
        role="tab"
        [id]="'filter-tab-' + tab.id"
        [attr.aria-selected]="filter() === tab.id"
        [attr.tabindex]="filter() === tab.id ? 0 : -1"
        (click)="setFilter(tab.id)"
        (keydown)="onFilterKeydown($event, tab.id)"
      >{{ tabLabel(tab) }}</button>
    }
  </div>

  @if (error()) {
    <div class="callout" role="alert" aria-live="assertive" style="margin-bottom:14px;">
      <app-icon name="warning" [size]="16" aria-hidden="true"></app-icon>
      <div>{{ error() }} <button type="button" class="inline-link" (click)="loadPending()">Retry</button></div>
    </div>
  }

  @if (loading()) {
    <div aria-busy="true" aria-label="Loading submissions">
      @for (n of [1, 2, 3]; track n) {
        <div class="skeleton" style="height:120px;margin-bottom:12px;" aria-hidden="true"></div>
      }
    </div>
  } @else if (filteredItems().length === 0) {
    <div class="empty" role="status">
      <div class="empty-ic">
        <app-icon name="check" [size]="22" aria-hidden="true"></app-icon>
      </div>
      <div style="font-weight:600;color:var(--ink);font-size:16px;">Queue clear</div>
      <div style="margin-top:6px;">Nothing waiting for review. Nicely done.</div>
    </div>
  } @else {
    <div style="display:flex;flex-direction:column;gap:12px;">
      @for (item of filteredItems(); track item.id) {
        <div class="queue-item fade-up">
          <div [class]="'risk-bar ' + riskBarClass(item.risk)"></div>

          <div class="ec-logo" style="width:42px;height:42px;">
            <app-icon [name]="typeIcon(item.entry)" [size]="20" aria-hidden="true"></app-icon>
          </div>

          <div style="flex:1;min-width:0;">
            <div style="display:flex;align-items:center;gap:10px;flex-wrap:wrap;">
              <span style="font-weight:600;font-size:16px;">{{ item.entry.name || 'Untitled' }}</span>
              @if (entrySlug(item.entry)) {
                <span class="mono" style="font-size:12.5px;color:var(--muted);">{{ entrySlug(item.entry) }}</span>
              }
              <app-type-badge [type]="entryType(item.entry)"></app-type-badge>
              <span class="badge" [class]="'badge-' + riskBadgeTone(item.risk)">
                {{ riskLabel(item.risk) }} risk
              </span>
            </div>

            @if (entrySummary(item.entry)) {
              <div class="ec-summary" style="margin-top:7px;">{{ entrySummary(item.entry) }}</div>
            }

            <div style="display:flex;gap:16px;margin-top:10px;flex-wrap:wrap;">
              <span class="stat">
                <app-icon name="user" [size]="14" aria-hidden="true"></app-icon>
                <span class="stat-val">{{ entryPublisher(item.entry) }}</span>
              </span>
              <span class="stat">
                <app-icon name="clock" [size]="14" aria-hidden="true"></app-icon>
                <span class="stat-val">{{ timeAgo(item.submittedAt) }}</span>
              </span>
              @if (entryParent(item.entry); as parent) {
                <span class="stat">
                  <app-icon name="server" [size]="14" aria-hidden="true"></app-icon>
                  <span class="stat-val">{{ parent }}</span>
                  <span class="stat-label">server</span>
                </span>
              }
              @if (entryTransports(item.entry).length > 0) {
                <span style="display:flex;gap:5px;">
                  @for (t of entryTransports(item.entry); track t) {
                    <span class="transport mono">{{ t }}</span>
                  }
                </span>
              }
              @if (entryToolCount(item.entry) > 0) {
                <span class="stat">
                  <app-icon name="tool" [size]="14" aria-hidden="true"></app-icon>
                  <span class="stat-val">{{ entryToolCount(item.entry) }}</span>
                  <span class="stat-label">tools</span>
                </span>
              }
              @if (entryAuth(item.entry); as auth) {
                <span class="stat">
                  <span class="stat-val">{{ auth }}</span>
                </span>
              }
            </div>

            @if (item.flags.length > 0) {
              <div class="flag-list">
                @for (flag of item.flags; track flag) {
                  <div class="flag" [class.high]="flagHighClass(item.risk)">
                    <app-icon name="warning" [size]="14" aria-hidden="true"></app-icon>
                    {{ flag }}
                  </div>
                }
              </div>
            }
          </div>

          <div style="display:flex;flex-direction:column;gap:8px;flex:none;width:150px;">
            <button
              class="btn btn-accent btn-sm btn-full"
              type="button"
              [disabled]="actionInProgress() === item.id"
              (click)="approve(item)"
            >
              <app-icon name="check" [size]="14" aria-hidden="true"></app-icon>
              Approve
            </button>
            <button
              class="btn btn-secondary btn-sm btn-full"
              type="button"
              [disabled]="actionInProgress() === item.id"
              (click)="requestChanges(item)"
            >
              <app-icon name="flag" [size]="14" aria-hidden="true"></app-icon>
              Request changes
            </button>
            <button
              class="btn btn-danger btn-sm btn-full"
              type="button"
              [disabled]="actionInProgress() === item.id"
              (click)="reject(item)"
            >
              <app-icon name="close" [size]="14" aria-hidden="true"></app-icon>
              Reject
            </button>
          </div>
        </div>
      }
    </div>
  }
</div>

@if (toast()) {
  <div
    class="fade-up"
    [attr.role]="toast()!.verdict.includes('failed') ? 'alert' : 'status'"
    aria-live="polite"
    style="position:fixed;bottom:24px;left:50%;transform:translateX(-50%);z-index:95;background:var(--ink);color:white;padding:12px 18px;border-radius:11px;box-shadow:var(--shadow-lg);display:flex;align-items:center;gap:10px;font-size:14px;"
  >
    <span
      [style.color]="toast()!.verdict.includes('failed') || toast()!.verdict === 'rejected' ? '#ff9b91' : '#86efac'"
      style="display:inline-flex;"
    >
      <app-icon
        [name]="toast()!.verdict.includes('failed') || toast()!.verdict === 'rejected' ? 'close' : 'check'"
        [size]="16"
        aria-hidden="true"
      ></app-icon>
    </span>
    <span><b>{{ toast()!.name }}</b> {{ toast()!.verdict }}</span>
  </div>
}

@if (rejectDialog(); as rd) {
  <div class="modal-overlay" (click)="cancelRejectDialog()">
    <div
      #rejectModal
      class="modal"
      role="dialog"
      aria-modal="true"
      [attr.aria-label]="rd.mode === 'changes' ? 'Request changes' : 'Reject submission'"
      (click)="$event.stopPropagation()"
      (keydown.escape)="cancelRejectDialog()"
    >
      <h2 class="modal-title">
        {{ rd.mode === 'changes' ? 'Request changes' : 'Reject submission' }}
      </h2>
      <p class="modal-sub">{{ rd.entry.entry.name }}</p>
      <label for="reject-reason" class="sr-only">
        {{ rd.mode === 'changes' ? 'Describe the changes required' : 'Reason for rejection' }}
      </label>
      <textarea
        id="reject-reason"
        class="input"
        rows="4"
        autofocus
        [ngModel]="rejectReason()"
        (ngModelChange)="rejectReason.set($event)"
        [attr.placeholder]="rd.mode === 'changes'
          ? 'Describe the changes required (min 10 characters)'
          : 'Reason for rejection (min 10 characters)'"
        aria-describedby="reject-error"
      ></textarea>
      @if (rejectError()) {
        <div id="reject-error" class="field-error" role="alert">{{ rejectError() }}</div>
      }
      <div class="modal-actions">
        <button type="button" class="btn btn-secondary btn-sm" (click)="cancelRejectDialog()">
          Cancel
        </button>
        <button type="button" class="btn btn-primary btn-sm" (click)="confirmRejectDialog()">
          {{ rd.mode === 'changes' ? 'Request changes' : 'Reject' }}
        </button>
      </div>
    </div>
  </div>
}

@if (approveDialog(); as entry) {
  <div class="modal-overlay" (click)="cancelApproveDialog()">
    <div
      #approveModal
      class="modal"
      role="dialog"
      aria-modal="true"
      aria-label="Confirm approval"
      (click)="$event.stopPropagation()"
      (keydown.escape)="cancelApproveDialog()"
    >
      <h2 class="modal-title">Publish to registry?</h2>
      <p class="modal-sub">
        <b>{{ entry.entry.name }}</b> will go live immediately. This cannot be undone from the queue.
      </p>
      @if (entry.flags.length > 0) {
        <div class="flag-list" style="margin-bottom: 12px">
          @for (flag of entry.flags; track flag) {
            <div class="flag" [class.high]="flagHighClass(entry.risk)">
              <app-icon name="warning" [size]="14" aria-hidden="true"></app-icon>
              {{ flag }}
            </div>
          }
        </div>
      }
      <div class="modal-actions">
        <button type="button" class="btn btn-secondary btn-sm" (click)="cancelApproveDialog()">
          Cancel
        </button>
        <button type="button" class="btn btn-accent btn-sm" (click)="confirmApproveDialog()">
          Approve and publish
        </button>
      </div>
    </div>
  </div>
}

@if (approveDialog(); as entry) {
  <div class="modal-overlay" (click)="cancelApproveDialog()">
    <div
      #approveModal
      class="modal"
      role="dialog"
      aria-modal="true"
      aria-label="Confirm approval"
      (click)="$event.stopPropagation()"
      (keydown.escape)="cancelApproveDialog()"
    >
      <h2 class="modal-title">Publish to registry?</h2>
      <p class="modal-sub">
        <b>{{ entry.entry.name }}</b> will go live immediately. This cannot be undone from the queue.
      </p>
      @if (entry.flags.length > 0) {
        <div class="flag-list" style="margin-bottom: 12px">
          @for (flag of entry.flags; track flag) {
            <div class="flag" [class.high]="flagHighClass(entry.risk)">
              <app-icon name="warning" [size]="14" aria-hidden="true"></app-icon>
              {{ flag }}
            </div>
          }
        </div>
      }
      <div class="modal-actions">
        <button type="button" class="btn btn-secondary btn-sm" (click)="cancelApproveDialog()">
          Cancel
        </button>
        <button type="button" class="btn btn-accent btn-sm" (click)="confirmApproveDialog()">
          Approve and publish
        </button>
      </div>
    </div>
  </div>
}

// project/admin.jsx
/* Admin / governance queue. */
function AdminPage({ onNav }) {
  const [items, setItems] = useState(window.REGISTRY.PENDING);
  const [filter, setFilter] = useState("all");
  const [toast, setToast] = useState(null);

  const act = (id, verdict) => {
    const item = items.find((x) => x.id === id);
    setItems(items.filter((x) => x.id !== id));
    setToast({ name: item.name, verdict });
    setTimeout(() => setToast(null), 2600);
  };

  const shown = filter === "all" ? items : items.filter((i) => i.type === filter || i.risk === filter);

  const KPIS = [
  { n: items.length, l: "Awaiting review", trend: null },
  { n: 8, l: "Published", trend: "+3 this week", up: true },
  { n: items.filter((i) => i.risk === "high").length, l: "High risk flagged", trend: null, danger: true },
  { n: "2.1k", l: "Avg time to review", suffix: "min", trend: "−18%", up: true }];


  return (
    <div className="container page">
      <div className="page-head" style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", flexWrap: "wrap", gap: 16 }}>
        <div>
          <div className="eyebrow">Governance</div>
          <h1 className="h1">Moderation queue</h1>
          <p className="lede">Review what publishers want to add. Approve, request changes, or reject — least privilege is the default.</p>
        </div>
        <Button variant="secondary" icon="shield" onClick={() => onNav({ view: "policy" })}>Policy settings</Button>
      </div>

      <div className="admin-stats">
        {KPIS.map((k, i) =>
        <div key={i} className="kpi">
            <div className="kpi-n" style={k.danger && k.n > 0 ? { color: "var(--danger)" } : {}}>{k.n}{k.suffix && <span style={{ fontSize: 14, color: "var(--muted)", fontWeight: 500 }}> {k.suffix}</span>}</div>
            <div className="kpi-l">{k.l}</div>
            {k.trend && <div className="kpi-trend" style={{ color: k.up ? "var(--ok)" : "var(--muted)" }}>{k.trend}</div>}
          </div>
        )}
      </div>

      <div className="tabs" style={{ marginBottom: 20 }} data-comment-anchor="31c7461117-div-44-7">
        {[{ id: "all", label: `All · ${items.length}` }, { id: "server", label: "Servers" }, { id: "tool", label: "Tools" }, { id: "skill", label: "Skills" }, { id: "high", label: "High risk" }].map((t) =>
        <div key={t.id} className={`tab ${filter === t.id ? "on" : ""}`} onClick={() => setFilter(t.id)}>{t.label}</div>
        )}
      </div>

      {shown.length === 0 ?
      <div className="empty">
          <div className="empty-ic"><Icon name="check" size={22} /></div>
          <div style={{ fontWeight: 600, color: "var(--ink)", fontSize: 16 }}>Queue clear</div>
          <div style={{ marginTop: 6 }}>Nothing waiting for review. Nicely done.</div>
        </div> :

      <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          {shown.map((item) =>
        <div key={item.id} className="queue-item fade-up">
              <div className={`risk-bar risk-${item.risk}`} />
              <div className="ec-logo" style={{ width: 42, height: 42 }}><Icon name={TYPE_META[item.type].icon} size={20} /></div>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" }}>
                  <span style={{ fontWeight: 600, fontSize: 16 }}>{item.name}</span>
                  <span className="mono" style={{ fontSize: 12.5, color: "var(--muted)" }}>{item.slug}</span>
                  <TypeBadge type={item.type} />
                  <Badge tone={item.risk === "high" ? "danger" : item.risk === "medium" ? "warn" : "ok"}>{item.risk} risk</Badge>
                </div>
                <div className="ec-summary" style={{ marginTop: 7 }}>{item.summary}</div>
                <div style={{ display: "flex", gap: 16, marginTop: 10, flexWrap: "wrap" }}>
                  <Stat icon="user" value={item.publisher} />
                  <Stat icon="clock" value={timeAgo(item.submitted)} />
                  {item.parent && <Stat icon="server" value={item.parent} label="server" />}
                  {item.transports && <span style={{ display: "flex", gap: 5 }}>{item.transports.map((t) => <Transport key={t} t={t} />)}</span>}
                  {item.toolCount > 0 && <Stat icon="tool" value={item.toolCount} label="tools" />}
                  {item.auth && <Stat value={item.auth} />}
                </div>
                {item.flags.length > 0 &&
            <div className="flag-list">
                    {item.flags.map((f, i) =>
              <div key={i} className={`flag ${item.risk === "high" ? "high" : ""}`}><Icon name="warning" size={14} />{f}</div>
              )}
                  </div>
            }
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8, flex: "none", width: 150 }}>
                <Button variant="accent" size="sm" icon="check" full onClick={() => act(item.id, "approved")}>Approve</Button>
                <Button variant="secondary" size="sm" icon="flag" full onClick={() => act(item.id, "changes requested")}>Request changes</Button>
                <Button variant="danger" size="sm" icon="close" full onClick={() => act(item.id, "rejected")}>Reject</Button>
              </div>
            </div>
        )}
        </div>
      }

      {toast &&
      <div style={{ position: "fixed", bottom: 24, left: "50%", transform: "translateX(-50%)", zIndex: 95, background: "var(--ink)", color: "white", padding: "12px 18px", borderRadius: 11, boxShadow: "var(--shadow-lg)", display: "flex", alignItems: "center", gap: 10, fontSize: 14 }} className="fade-up">
          <Icon name={toast.verdict === "rejected" ? "close" : "check"} size={16} stroke={2.2} style={{ color: toast.verdict === "rejected" ? "#ff9b91" : "#86efac" }} />
          <span><b>{toast.name}</b> {toast.verdict}</span>
        </div>
      }
    </div>);

}

Object.assign(window, { AdminPage });
